import { Station } from "./types";

export const demoStations: Station[] = [
  {
    id: "in-blr-001",
    name: "VoltHub Indiranagar",
    city: "Bangalore",
    state: "Karnataka",
    location: { lat: 12.9784, lng: 77.6408 },
    totalPorts: 12,
    availablePorts: 4,
    avgSessionMinutes: 20,
    chargerKW: 150,
    batteryCapacityKWh: 80,
    queueLength: 2,
    status: "Free",
    operator: "Tata Power",
    connectorType: "CCS2",
    distanceKm: 4.2,
    usageType: "Public"
  },
  {
    id: "in-blr-002",
    name: "Electron Plaza Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    location: { lat: 12.9352, lng: 77.6245 },
    totalPorts: 6,
    availablePorts: 0,
    avgSessionMinutes: 25,
    chargerKW: 250,
    batteryCapacityKWh: 80,
    queueLength: 5,
    status: "Busy",
    operator: "SNA Charge",
    connectorType: "NACS/CCS2",
    distanceKm: 2.1,
    usageType: "Public"
  },
  {
    id: "in-blr-003",
    name: "GridLink MG Road",
    city: "Bangalore",
    state: "Karnataka",
    location: { lat: 12.9756, lng: 77.5937 },
    totalPorts: 20,
    availablePorts: 12,
    avgSessionMinutes: 30,
    chargerKW: 120,
    batteryCapacityKWh: 80,
    queueLength: 0,
    status: "Free",
    operator: "Zeon Charging",
    connectorType: "CCS2",
    distanceKm: 6.8,
    usageType: "Commercial"
  },
  {
    id: "in-blr-004",
    name: "Pulse Station Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    location: { lat: 12.9698, lng: 77.7499 },
    totalPorts: 8,
    availablePorts: 1,
    avgSessionMinutes: 18,
    chargerKW: 350,
    batteryCapacityKWh: 80,
    queueLength: 3,
    status: "Charging",
    operator: "ElectreeFI",
    connectorType: "CCS2",
    distanceKm: 12.4,
    usageType: "Public"
  },
  {
    id: "in-blr-005",
    name: "Static Hub Jayanagar",
    city: "Bangalore",
    state: "Karnataka",
    location: { lat: 12.9250, lng: 77.5938 },
    totalPorts: 10,
    availablePorts: 5,
    avgSessionMinutes: 22,
    chargerKW: 180,
    batteryCapacityKWh: 80,
    queueLength: 1,
    status: "Free",
    operator: "Fortum",
    connectorType: "CCS2",
    distanceKm: 8.1,
    usageType: "Public"
  }
];

export const MOCK_STATIONS = demoStations;
