import { Station } from "./types";

// Representative dataset based on the requested fields and region
export const demoStations: Station[] = [
  {
    id: "in-mng-001",
    name: "Tata Power Charging Station - Adyar",
    city: "Mangalore",
    state: "Karnataka",
    latitude: 12.8687,
    longitude: 74.9220,
    location: { lat: 12.8687, lng: 74.9220 },
    totalPorts: 4,
    availablePorts: 2,
    avgSessionMinutes: 45,
    chargerKW: 50,
    batteryCapacityKWh: 80,
    queueLength: 1,
    status: "Free",
    operator: "Tata Power",
    connectorType: "CCS2",
    distanceKm: 0, // Calculated dynamically
    usageType: "Public"
  },
  {
    id: "in-mng-002",
    name: "Zeon Charging - Bharat Mall",
    city: "Mangalore",
    state: "Karnataka",
    latitude: 12.8890,
    longitude: 74.8450,
    location: { lat: 12.8890, lng: 74.8450 },
    totalPorts: 2,
    availablePorts: 0,
    avgSessionMinutes: 30,
    chargerKW: 60,
    batteryCapacityKWh: 80,
    queueLength: 2,
    status: "Busy",
    operator: "Zeon",
    connectorType: "CCS2",
    distanceKm: 0,
    usageType: "Public"
  },
  {
    id: "in-mng-003",
    name: "SNA Charge Hub - Bejai",
    city: "Mangalore",
    state: "Karnataka",
    latitude: 12.8890, // Same lat/lng for grouping demo
    longitude: 74.8450,
    location: { lat: 12.8890, lng: 74.8450 },
    totalPorts: 4,
    availablePorts: 1,
    avgSessionMinutes: 20,
    chargerKW: 120,
    batteryCapacityKWh: 80,
    queueLength: 0,
    status: "Free",
    operator: "SNA",
    connectorType: "NACS",
    distanceKm: 0,
    usageType: "Public"
  },
  {
    id: "in-mng-004",
    name: "Fortum Charge & Drive - Forum Fiza",
    city: "Mangalore",
    state: "Karnataka",
    latitude: 12.8617,
    longitude: 74.8360,
    location: { lat: 12.8617, lng: 74.8360 },
    totalPorts: 6,
    availablePorts: 3,
    avgSessionMinutes: 25,
    chargerKW: 50,
    batteryCapacityKWh: 80,
    queueLength: 0,
    status: "Free",
    operator: "Fortum",
    connectorType: "CCS2",
    distanceKm: 0,
    usageType: "Public"
  },
  {
    id: "in-mng-005",
    name: "KSEB Charging Station - Thokkottu",
    city: "Mangalore",
    state: "Karnataka",
    latitude: 12.8250,
    longitude: 74.8620,
    location: { lat: 12.8250, lng: 74.8620 },
    totalPorts: 2,
    availablePorts: 1,
    avgSessionMinutes: 50,
    chargerKW: 30,
    batteryCapacityKWh: 80,
    queueLength: 1,
    status: "Delayed",
    operator: "KSEB",
    connectorType: "CCS2",
    distanceKm: 0,
    usageType: "Commercial"
  }
];

export const MOCK_STATIONS = demoStations;
